### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/async-append-only-log#15]
I got this in manyverse:

```
01-04 19:57:01.221  7006  7063 E NODEJS-MOBILE: TypeError: Cannot read property 'slice' of undefined
01-04 19:57:01.221  7006  7063 E NODEJS-MOBILE:     at Request._callback (/data/data/se.manyver/files/nodejs-project/index.js:41590:68)
01-04 19:57:01.221  7006  7063 E NODEJS-MOBILE:     at Request.Trwq+KqeWzxsbUet+Omb+wC9uH2QMBcZNBUiXOCqCv4=.Request.callback (/data/data/se.manyver/files/nodejs-project/index.js:45141:8)
01-04 19:57:01.221  7006  7063 E NODEJS-MOBILE:     at onwrite (/data/data/se.manyver/files/nodejs-project/index.js:75540:31)
01-04 19:57:01.221  7006  7063 E NODEJS-MOBILE:     at FSReqCallback.wrapper [as oncomplete] (fs.js:615:5)
```

https://github.com/ssb-ngi-pointer/async-append-only-log/blob/8d6626831cd0c61ab97c45d31a0a4717f2723f26/index.js#L280

**Comment by arj03** [comment]
Yeah, that looks like a bug. The most difficult will be to reproduce the problem. It seems to happen when you have multiple writers.
